### ISSUE TITLE
支持C20

### ISSUE THREAD

**Issue by yunate** [soui4/soui#13]
看起来soui4使用的是C14标准, 有计划支持C20吗?

**Comment by setoutsoft** [comment]
soui使用的c99语法，个别代码会可选支持C11，为的就是对编译器的要求最小。不会在内部使用c20等新语法。

**Comment by yunate** [comment]
不是要求使用c20等新语法, 只是希望编译的时候将CPP的标准改为20也能编译成功, 因为在使用SOUI这个库的同时,也会使用其他的库, 这些库要求C20编译. 一般来说项目直接升级到C20就能直接使用的, 但是貌似C20下有个别语法不兼容c11

**Comment by setoutsoft** [comment]
刚修改了一个版本，修复了几个不兼容c20的地方。目前测试正常。
