### ISSUE TITLE
No support for the open source MinGW64 compiler?

### ISSUE THREAD

**Issue by tn1997tn** [soui4/soui#6]
I was able to have cmake configured and generated the ninja build script. But when actually started the build, it failed with:

```
[1/1025] Generating C unity source third-part/zlib/cotire/zlib_C_unity.c
[2/1025] Generating C prefix source third-part/zlib/cotire/zlib_C_prefix.c
[3/1025] Generating C prefix header third-part/zlib/cotire/zlib_C_prefix.h
[4/1025] Building C precompiled header third-part/zlib/cotire/zlib_C_prefix.h.gch
[5/1025] Building C object third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj
FAILED: third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj
C:\msys64\mingw64\bin\cc.exe -DUNICODE -D_CRT_SECURE_NO_WARNINGS -D_UNICODE  /MP /wd4100 /wd4189 /wd4996 -Winvalid-pch -include C:/msys64/home/Administrator/soui/build/third-part/zlib/cotire/zlib_C_prefix.h -MD -MT third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj -MF third-part\zlib\CMakeFiles\zlib.dir\adler32.c.obj.d -o third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj -c C:/msys64/home/Administrator/soui/third-part/zlib/adler32.c
cc.exe: warning: /MP: linker input file unused because linking not done
cc.exe: error: /MP: linker input file not found: No such file or directory
cc.exe: warning: /wd4100: linker input file unused because linking not done
cc.exe: error: /wd4100: linker input file not found: No such file or directory
cc.exe: warning: /wd4189: linker input file unused because linking not done
cc.exe: error: /wd4189: linker input file not found: No such file or directory
cc.exe: warning: /wd4996: linker input file unused because linking not done
cc.exe: error: /wd4996: linker input file not found: No such file or directory
ninja: build stopped: subcommand failed.
```

Noticed the build options are all MSVC specific?

**Comment by tn1997tn** [comment]
This is the faulty lines on `global.cmake`:

https://github.com/SOUI2/soui/blob/master/__cmake/global.cmake#L35

Wrap them in `if (MSVC)` and `endif()` then I could continue to build. In the process, I discovered this library use so much MSVC specific stuffs, so it's practically impossible to support MinGW64 without a big refactoring of code.

**Comment by setoutsoft** [comment]
Frankly to say, I'm not familiar with MingW64. soui4 removed all of "__supper" in core module.  I think this will be important for someone to add supporting for MinGW64.

**Comment by hgntn** [comment]
MinGW-w64 doesn't support MFC or ATL. If your library uses any of them (I think very likely) then it's no hope. MSVC specific extensions like `__pragma` and `__super` will also cause problems as MinGW-w64 doesn't support them. On MinGW-w64, people use Win32++ as an alternative: https://win32-framework.sourceforge.net/

**Comment by setoutsoft** [comment]
soui does not depend on mfc or atl, but "#pragma once" is widely used. Is it a problem?

**Comment by tn1997tn** [comment]
> soui does not depend on mfc or atl, but "#pragma once" is widely used. Is it a problem?

MinGW supports "#pragma once". If your project doesn't use either mfc or atl then you could try to build it on MSYS2 MINGW64 (remember the Shell is MSYS2 MINGW64, not MSYS2 MSYS). If your project uses UCRT then the MSYS2 UCRT64 Shell or MSYS2 CLANG64 Shell should be used instead. You have to install the needed packages first before starting the build. MSYS2 uses the pacman package manager of Arch Linux with many packages available, there are plenty of documents on the internet so it's not a problem setting it up. Many of the software on your third-part directory already packaged by MSYS2. On MSYS2, packages should be preferred instead of including your own version of third party software and compile from source.

**Comment by tn1997tn** [comment]
As I recall the most troubled thing before I could actually compile SOUI itself on MSYS2 is the third-part software. I have to edit CMakeLists.txt to comment out most of them because they don't build on MSYS2. Some third-part software like 7zip requires MFC (or ATL, I'm not really remember). If you only need the DLL then you don't have to compile the GUI part of it I think (most of the time people on need the DLL). MSYS2 MINGW64 has a package for 7zip:

https://packages.msys2.org/package/mingw-w64-x86_64-7zip?repo=mingw64

The package included the DLL. If you gonna to use UCRT64 or CLANG64 then change the prefix `mingw-w64-x86_64-` on the package name to `mingw-w64-ucrt-x86_64-` or `mingw-w64-clang-x86_64-`.

**Comment by setoutsoft** [comment]
All of third-party package except for skia are unnecessary for soui core library.
Soui uses idea of COM to build plugins. Most of them are served for some COM object.
So, you can ignore most of them.

**Comment by tn1997tn** [comment]
> All of third-party package except for skia are unnecessary for soui core library. Soui uses idea of COM to build plugins. Most of them are served for some COM object. So, you can ignore most of them.

MSYS2 MINGW64 has a package for skia: https://packages.msys2.org/package/mingw-w64-x86_64-skia

**Comment by setoutsoft** [comment]
The used skia version had been modified by me to adapt for soui render. So, you have to build it from source code provided by this repo.

**Comment by tn1997tn** [comment]
> The used skia version had been modified by me to adapt for soui render. So, you have to build it from source code provided by this repo.

The source code provided by this repo doesn't build on MSYS2 MINGW64.

**Comment by setoutsoft** [comment]
If this is true, it seems impossible for building soui use mingw now.

**Comment by tn1997tn** [comment]
> If this is true, it seems impossible for building soui use mingw now.

It seems skia doesn't build out of the box on MSYS2 MINGW64. It needs to be patched:

https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-skia

**Comment by setoutsoft** [comment]
I shall be happy to answer your questions about code of soui.
If you are interested in translating building of soui to mingw32/64, considering I'm blind about mingw,  I'm afraid I can't do it myself.
The skia version used in soui is relative old. It's based on a commit at 2014/9/25. I don't think the patch you provided may be right.
