### ISSUE TITLE
How soui compared to other direct ui?

### ISSUE THREAD

**Issue by hgntn** [soui4/soui#8]
Since I commented on an issue on soui repo, Github started to suggest me other direct ui.

https://github.com/simdsoft/REDM

https://github.com/FSMargoo/VuiLib

The original DuiLib (https://github.com/duilib/duilib) is no longer developed but the forks are still active:

https://github.com/qdtroy/DuiLib_Ultimate

https://github.com/netease-im/NIM_Duilib_Framework/tree/master/duilib

https://github.com/TencentCloud/TIMSDK/tree/master/Windows/Demo/Basic/duilib

**Comment by setoutsoft** [comment]
REDM was modified from soui 1.x.
In my opinion, the basic framework used in duilib is too simple to support big project. 
VuiLib seems new to me. I have no idea about it.

**Comment by hgntn** [comment]
> REDM was modified from soui 1.x.

Do you have soui 1.x repo on Github?

**Comment by setoutsoft** [comment]
soui1.x was lost. soui2 is similar to its old version. You can check code of soui2 to make your judgement.
soui2:  https://github.com/SOUI2/soui
